const NOT_FOUND = 404;
const BAD_REQUEST = 400;
const DEFAULT_ERROR = 500;
const AUTH_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const CONFLICT_ERROR = 409;
export {
  NOT_FOUND, BAD_REQUEST, DEFAULT_ERROR, AUTH_ERROR, FORBIDDEN_ERROR, CONFLICT_ERROR,
};
